name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          if [ -d "LyricInfo-57" ]; then cd LyricInfo-57; fi
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LyricInfo-Output
          path: |
            **/app/build/outputs/apk/**/*.apk
            **/app/build/outputs/apk/**/*.zip
            **/app/build/outputs/**/*.txt
            **/build/outputs/**/*.apk
